title: Stellar mass dependance on disc photoevaporation
author: Giovanni Picogna
name: GiovanniPicogna
email: giovanni.picogna@pm.me
description: Giovanni
show_excerpts: false

minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: giovannipicogna
    github:  GiovanniPicogna

#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
